#!/bin/sh

set -e

host=$(env | grep _TCP_ADDR | cut -d = -f 2)
port=$(env | grep _TCP_PORT | cut -d = -f 2)

echo -n "waiting for TCP connection to $host:$port..."

# See http://tldp.org/LDP/abs/html/devref1.html for description of this syntax.
# https://github.com/dominionenterprises/tol-api-php/blob/master/tests/provisioning/set-env.sh
while ! exec 6<>/dev/tcp/$host/$port; do
  echo -n .
  sleep 1
done

echo 'ok'
